### ISSUE TITLE
Is there any way to add the plugin to macOS?

### ISSUE THREAD

**Issue by mattisssa** [segment-integrations/analytics-swift-facebook-app-events#4]
Hey! I have a macOS application that uses Segment to track events. It works fine for Amplitude destination but to add Facebook App Events destination I should have FB SDK inside _(that as I understand doesn't support the macOS platform)_

**Comment by alanjcharles** [comment]
Hi @mattisssa ! Unfortunaly, there is not way to support the Facebook App Events Destination on MacOS because, to your point, they don't support MacOS. Hope this helps!
